services:
  mmf-shamil-dev:
    container_name: mmf-shamil-dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - 8001:8001

  mmf-shamil-dev-db:
    image: mongo:6-jammy
    container_name: mmf-shamil-dev-db
    restart: always
    volumes: 
      - db:/data/db

  mmf-shamil-redis-service:
    container_name: mmf-shamil-redis-service
    image: redis
    environment:
      - REDIS_PASSWORD=password

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      
volumes:
  db:
    driver: local